# [Info]
# 左上角标题
site_name: SHANGJU WEBSITE
site_url: https://macoding1994.github.io
site_author: SHANGJU
site_description: SHANGJU WEBSITE
repo_url: https://github.com/macoding1994

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - toc.follow
    - toc.integrate

nav:
  - Home: index.md
  - Me:
     - cybersecurity-portfolio/about_me.md
     - cybersecurity-portfolio/technical_skills.md
     - cybersecurity-portfolio/project_experience.md
     - cybersecurity-portfolio/learning_journey.md
     - cybersecurity-portfolio/career_objective.md

  - Blog:
     - blog/about_me.md

plugins:
  - search:
  - social:
      cards_layout: default

extra:
  social:
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@squidfunk