# [Info]
# 左上角标题
site_name: SHANGJU WEBSITE
site_url: https://macoding1994.github.io/cybersecurity-portfolio
site_author: SHANGJU
site_description: SHANGJU WEBSITE
repo_url: https://github.com/macoding1994

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - toc.follow
    - toc.integrate

nav:
  - Home: index.md
  - Me:
     - me/about_me.md
     - me/technical_skills.md
     - me/project_experience.md
     - me/learning_journey.md
     - me/career_objective.md

  - Networking & Security:
     - Networking & Security/Firewalld.md
     - Networking & Security/General.md
     - Networking & Security/Host Files.md
     - Networking & Security/Netcat.md
     - Networking & Security/Networking.md
     - Networking & Security/SSH & Port Forwarding.md
     - Networking & Security/SSH Server.md
     - Networking & Security/Using ADB.md
     - Networking & Security/Using Netsh.md

plugins:
  - search:
  - social:
      cards_layout: default

extra:
  social:
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@squidfunk